name: Publish

on:
  push:
    tags:
    - '*.*.*'

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ github.repository_owner }}/gitea-runner-windows
          tags: ${{ github.ref_name }}, latest
          registry: docker.io
          buildArgs: SERVERCORE_VERSION="ltsc2022",RUNNER_VERSION="${{ github.ref_name }}"
