name: Publish

on: [release]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & push (ltsc2022)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: tiobesoftware/github-runner-windows
          tags: ${{ github.ref }}-20H2
          registry: docker.io
          buildArgs: |
            SERVERCORE_VERSION="ltsc2022"
            RUNNER_VERSION="${{ github.ref }}"
      - name: Build & push (20H2)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: tiobesoftware/github-runner-windows
          tags: ${{ github.ref }}, latest
          registry: docker.io
          buildArgs: |
            SERVERCORE_VERSION="20H2"
            RUNNER_VERSION="${{ github.ref }}"
